### PR TITLE
Check pending Django migrations in CI

### PR DESCRIPTION
**Pull request by fmrsabino**
- Add step to CI to check if there are any migrations that should've been created and were not created (without creating them)

### CODE REVIEW

**Comment by fmrsabino** [comment]
@Uxio0 the CI is failing as expected. A missing migration was neither created nor applied.

This is fixed here: https://github.com/gnosis/safe-config-service/pull/184

**Comment by Uxio0** [comment]
We already talked about it when setting up the CI: `python manage.py check` 😉

**Comment by Uxio0** [comment]
I didn't know about this:

```
      - name: Check pending migrations
        run: python src/manage.py makemigrations --check --dry-run
```

I will add it asap on tx service CI too

**Review by Uxio0 — APPROVED** [review]
Nice!

**Comment by fmrsabino** [comment]
@Uxio0 Rebased to `main` after applying the missing migration. So the correct CI output should now be green 🤞

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
